### ISSUE TITLE
是否太強

### ISSUE THREAD

**Issue by lamperder** [5upergeo/5uperReshape#1]
會不會太強了

**Comment by lamperder** [comment]
@laurashley 一定要這麼強嗎?

**Comment by lamperder** [comment]
@HuskyHsu @laurashley @wey1018 出來面對啊

**Comment by HuskyHsu** [comment]
歐啦啦啦!!!!!!!!

**Comment by lamperder** [comment]
萬歲

**Comment by laurashley** [comment]
給我一個月 至少

**Comment by lamperder** [comment]
@laurashley 是否

**Comment by laurashley** [comment]
試用過後非常好上手，只要手指頭按一按，就跑出結果了呢~~~~~~ 還有進度百分比可供參考，實在是相當推薦~~~~~~建議走過路過別錯過，一定要clone下來試試!

**Comment by lamperder** [comment]
@laurashley 在強幾點的啦!!?
